# Generated by Django 4.1.5 on 2023-01-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professional", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("services", models.ManyToManyField(to="services.service")),
            ],
        ),
    ]
