# Generated by Django 4.1.5 on 2023-01-31 02:23

import customers.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("dni", "DNI"), ("cuit", "CUIT"), ("cuil", "CUIL")],
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("country_code", models.CharField(max_length=5)),
                ("area_code", models.CharField(max_length=5)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default=customers.models.get_default_profile_image,
                        max_length=255,
                        null=True,
                        upload_to=customers.models.get_profile_image_filepath,
                        verbose_name="Foto de perfil",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
