# Generated by Django 4.1.5 on 2023-02-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0002_customer_groups_customer_is_active_customer_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user_permissions",
        ),
    ]
