# Generated by Django 4.1.5 on 2023-02-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_customer_groups_remove_customer_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
