# Generated by Django 4.1.5 on 2023-02-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_managers_customer_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(default="-", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
