# Generated by Django 4.1.5 on 2023-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0006_alter_customer_managers_remove_customer_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=25),
        ),
    ]
